config:
  MD004: false
  MD012: false
  MD013: false
  MD022: false
  MD032: false
  MD033: false
  MD036: false
  MD003: false
  MD009: false
  MD024: false
  MD026: false
  MD031: false
  MD040: false
  MD058: false
  MD025: false
  MD034: false
  MD029: false
