#!/usr/bin/env python3
"""Generate per-project audit logs under agents/audits/."""

from __future__ import annotations

import sys
from pathlib import Path

from utils import (
    AGENTS_DIR,
    TEMPLATES_DIR,
    ensure_dir,
    project_display_name,
    read_readme_summary,
    today,
    write_md,
)


def load_template() -> str:
    template_path = TEMPLATES_DIR / "AUDIT-log.md"
    if not template_path.exists():
        raise FileNotFoundError(f"Missing template: {template_path}")
    return template_path.read_text(encoding="utf-8")


def build_summary_block(project_dir: Path) -> str:
    readme = project_dir / "README.md"
    summary = read_readme_summary(readme)
    tasks_path = project_dir / "tasks.md"
    sessions_path = project_dir / "sessions"

    lines = [
        "## Project Summary",
        "",
        summary,
        "",
        "### Artifacts",
        f"- Tasks — `{tasks_path.relative_to(AGENTS_DIR)}`",
        f"- Sessions — `{sessions_path.relative_to(AGENTS_DIR)}/`",
        "",
    ]
    return "\n".join(lines)


def render_project_audit(project_dir: Path, template: str) -> str:
    project_name = project_display_name(project_dir)
    replacements = {
        "# Project — AUDIT Log": f"# {project_name} — AUDIT Log",
        "**Date:** YYYY-MM-DD": f"**Date:** {today()}",
        "**LLM Auditor:** [Name / Model]": "**LLM Auditor:** Automation Sync",
        "**Project:** [Project Name]": f"**Project:** {project_name}",
        "**Author:** [Your Name]": "**Author:** Agent Automation",
    }
    content = template
    for src, dst in replacements.items():
        content = content.replace(src, dst, 1)

    summary_block = build_summary_block(project_dir)
    marker = "\n---\n"
    if marker in content:
        head, tail = content.split(marker, 1)
        content = f"{head}\n\n{summary_block}{marker}{tail}"
    else:
        content = f"{content}\n\n{summary_block}"

    footer = "\n> Generated by `agents/scripts/generate_audit.py`.\n"
    if footer not in content:
        content = f"{content.rstrip()}{footer}"
    return content


def main() -> int:
    projects_dir = AGENTS_DIR / "projects"
    audits_dir = ensure_dir(AGENTS_DIR / "audits")
    template = load_template()
    generated = 0

    for project_dir in sorted(projects_dir.iterdir()):
        if not project_dir.is_dir():
            continue
        content = render_project_audit(project_dir, template)
        output_path = audits_dir / f"{project_dir.name}.md"
        if output_path.exists() and output_path.read_text(encoding="utf-8") == content:
            continue
        write_md(output_path, content)
        generated += 1
        print(f"✅ audit updated for {project_dir.name}")

    if not generated:
        print("No audit changes detected.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
