// src/ArenaConfig.js
// Deterministic arena configuration schema
// Generated by LobbyScene and consumed by StageGenerator (Arena Compiler)

const SAFE_ZONE_DEFAULTS = [
  { radius: 40, durationSeconds: 60, damagePerSecond: 2 },
  { radius: 25, durationSeconds: 45, damagePerSecond: 5 },
  { radius: 14, durationSeconds: 30, damagePerSecond: 10 },
  { radius: 6,  durationSeconds: 20, damagePerSecond: 20 },
  { radius: 2,  durationSeconds: 10, damagePerSecond: 50 },
];

/**
 * Seeded pseudo-random number generator (Mulberry32).
 * Produces deterministic sequences from an integer seed.
 */
function seededRng(seed) {
  let s = seed >>> 0;
  return () => {
    s += 0x6d2b79f5;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = t + Math.imul(t ^ (t >>> 7), 61 | t) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * ArenaConfig
 * Fully validated, deterministic schema for one match arena.
 * Mirrors the TypeScript interface described in the house spec but in plain JS.
 */
export class ArenaConfig {
  /**
   * @param {object} opts
   * @param {number}  [opts.seed=1]         Integer seed for deterministic generation
   * @param {number}  [opts.size=80]         Half-extent of the arena (world units)
   * @param {number}  [opts.numPlayers=12]   Total player count (human + bots)
   * @param {number}  [opts.coverCount=24]   Number of cover obstacle clusters
   * @param {number}  [opts.terrainBands=3]  How many height-band rings to generate
   */
  constructor({
    seed = 1,
    size = 80,
    numPlayers = 12,
    coverCount = 24,
    terrainBands = 3,
  } = {}) {
    this.seed = seed;
    this.size = size;
    this.numPlayers = numPlayers;

    const rng = seededRng(seed);
    this._rng = rng;

    // ── Bounds ────────────────────────────────────────────────────────────────
    this.bounds = { min: -size, max: size };

    // ── Spawn Points ──────────────────────────────────────────────────────────
    this.spawnPoints = this._generateSpawns(numPlayers, size, rng);

    // ── Bot Waypoints ─────────────────────────────────────────────────────────
    this.botWaypoints = this._generateWaypoints(20, size, rng);

    // ── Cover Clusters ────────────────────────────────────────────────────────
    this.coverClusters = this._generateCoverClusters(coverCount, size, rng);

    // ── Terrain Bands ─────────────────────────────────────────────────────────
    this.terrainBands = this._generateTerrainBands(terrainBands, size, rng);

    // ── Safe Zone Phases ─────────────────────────────────────────────────────
    this.safeZonePhases = SAFE_ZONE_DEFAULTS.map((phase, i) => ({
      phase: i + 1,
      ...phase,
      centerX: (rng() - 0.5) * size * 0.5,
      centerZ: (rng() - 0.5) * size * 0.5,
    }));

    // Current safe-zone state (mutated during match)
    this.safeZone = {
      phaseIndex: 0,
      currentRadius: SAFE_ZONE_DEFAULTS[0].radius,
      centerX: this.safeZonePhases[0].centerX,
      centerZ: this.safeZonePhases[0].centerZ,
      phaseTimer: 0,
      shrinking: false,
    };

    console.log(
      `[ArenaConfig] Generated: seed=${seed}, size=${size}, ` +
      `spawns=${this.spawnPoints.length}, covers=${this.coverClusters.length}`
    );
  }

  // ── Generators ──────────────────────────────────────────────────────────────

  _generateSpawns(count, size, rng) {
    const spawns = [];
    const spread = size * 0.75;
    const angleStep = (Math.PI * 2) / count;
    for (let i = 0; i < count; i++) {
      const angle = angleStep * i + (rng() - 0.5) * 0.4;
      const r = spread * 0.6 + rng() * spread * 0.3;
      spawns.push({
        x: Math.cos(angle) * r,
        y: 0,
        z: Math.sin(angle) * r,
        rotation: -angle + Math.PI,
      });
    }
    return spawns;
  }

  _generateWaypoints(count, size, rng) {
    const wps = [];
    for (let i = 0; i < count; i++) {
      wps.push({
        x: (rng() * 2 - 1) * size * 0.85,
        y: 0,
        z: (rng() * 2 - 1) * size * 0.85,
      });
    }
    return wps;
  }

  _generateCoverClusters(count, size, rng) {
    const clusters = [];
    for (let i = 0; i < count; i++) {
      const cx = (rng() * 2 - 1) * size * 0.8;
      const cz = (rng() * 2 - 1) * size * 0.8;
      const numPieces = 1 + Math.floor(rng() * 4);
      const pieces = [];
      for (let j = 0; j < numPieces; j++) {
        pieces.push({
          offsetX: (rng() - 0.5) * 6,
          offsetZ: (rng() - 0.5) * 6,
          width:  1 + rng() * 3,
          height: 1 + rng() * 2,
          depth:  0.5 + rng() * 1,
          rotation: rng() * Math.PI,
        });
      }
      clusters.push({ cx, cz, pieces });
    }
    return clusters;
  }

  _generateTerrainBands(bands, size, rng) {
    const result = [];
    for (let b = 0; b < bands; b++) {
      const innerR = (size / (bands + 1)) * (b + 0.5);
      const outerR = (size / (bands + 1)) * (b + 1.5);
      const elevationDelta = (rng() - 0.5) * 1.5;
      result.push({ innerR, outerR, elevationDelta });
    }
    return result;
  }

  // ── Helpers ─────────────────────────────────────────────────────────────────

  /** Check if a world-space position is inside the current safe zone. */
  isInsideSafeZone(x, z) {
    const { currentRadius, centerX, centerZ } = this.safeZone;
    const dx = x - centerX;
    const dz = z - centerZ;
    return Math.sqrt(dx * dx + dz * dz) <= currentRadius;
  }

  /** Serialise to plain object (for A2A events). */
  toJSON() {
    return {
      seed: this.seed,
      size: this.size,
      numPlayers: this.numPlayers,
      bounds: this.bounds,
      spawnPoints: this.spawnPoints,
      botWaypoints: this.botWaypoints,
      coverClusters: this.coverClusters,
      terrainBands: this.terrainBands,
      safeZonePhases: this.safeZonePhases,
    };
  }

  /** Rebuild from a plain JSON object (e.g. received over the event bus). */
  static fromJSON(obj) {
    const cfg = new ArenaConfig({ seed: obj.seed, size: obj.size, numPlayers: obj.numPlayers });
    // Overwrite generated fields with the serialised ones for exact parity
    Object.assign(cfg, obj);
    return cfg;
  }
}
